### ISSUE TITLE
cellranger scATAC workflow

### ISSUE THREAD

**Issue by wjyzidane** [klarman-cell-observatory/cumulus#1]
Hello,

I used cellranger_workflow on Terra for my 10x scATAC-seq data. It worked pretty well last month but it gives me an error as below. may I know what could be the possible problem?

2019/10/04 21:48:39 Starting container setup. 2019/10/04 21:48:42 Done container setup. 2019/10/04 21:48:43 Starting localization. 2019/10/04 21:48:55 Localizing input gs://fc-6cb77780-e1cc-4346-8964-cce827d68568/5e52ff5e-a9e1-4f44-b23a-f179a7b74a13/cellranger_workflow/e62b09d8-4d10-468f-9e51-cea18ab5a217/call-generate_bcl_csv/script -> /cromwell_root/script 2019/10/04 21:48:56 Localizing input gs://fc-6cb77780-e1cc-4346-8964-cce827d68568/cellrangersamplesheet.csv -> /cromwell_root/fc-6cb77780-e1cc-4346-8964-cce827d68568/cellrangersamplesheet.csv 2019/10/04 21:49:02 Done localization. 
2019/10/04 21:49:03 Running user action: docker run -v /mnt/local-disk:/cromwell_root --entrypoint= sccloud/cellranger@sha256:12d71966d2579f9d9ad8af0047df02057ef7101463f25d9a6dc0fef0b7c0a13f /bin/bash /cromwell_root/script Traceback (most recent call last): File "<stdin>", line 10, in <module> File "/opt/conda/lib/python3.7/site-packages/pandas/core/series.py", line 3825, in map new_values = super()._map_values(arg, na_action=na_action) File "/opt/conda/lib/python3.7/site-packages/pandas/core/base.py", line 1300, in _map_values new_values = map_f(values, mapper) File "pandas/_libs/lib.pyx", line 2228, in pandas._libs.lib.map_infer File "<stdin>", line 10, in <lambda> File "/opt/conda/lib/python3.7/re.py", line 192, in sub return _compile(pattern, flags).sub(repl, string, count) TypeError: expected string or bytes-like object 
2019/10/04 21:49:15 Starting delocalization. 2019/10/04 21:49:16 Delocalizing output /cromwell_root/run_ids.txt -> gs://fc-6cb77780-e1cc-4346-8964-cce827d68568/5e52ff5e-a9e1-4f44-b23a-f179a7b74a13/cellranger_workflow/e62b09d8-4d10-468f-9e51-cea18ab5a217/call-generate_bcl_csv/run_ids.txt Required file output '/cromwell_root/run_ids.txt' does not exist.

Also, here is the content in my sample sheet.

Sample | Reference | Flowcell | Lane | Index | Data type
-- | -- | -- | -- | -- | --
DNA_Lib 10696 | hg19_atac_v1.0.1 | gs://fc-6cb77780-e1cc-4346-8964-cce827d68568/H2NYMBGXC/190925_SL-NXC_0725_AH2NYMBGXC/ | 1-4 | SI-NA-A1 | atac

Thanks,

**Comment by joshua-gould** [comment]
Can you please share the actual sample sheet file? Thanks.

**Comment by wjyzidane** [comment]
Here you go.

**Comment by joshua-gould** [comment]
It looks like you forgot the attachment. Thanks.

**Comment by wjyzidane** [comment]
I can still see the attachment in the email but it looks like it can not be uploaded to GitHub. Do you have another email address that I can send to you directly.

Thanks,
Jingyi

**Comment by joshua-gould** [comment]
You can email us at cumulus at broadinstitute dot org
