### ISSUE TITLE
cellranger: most cells called by gene expression are missing from adt output csv

### ISSUE THREAD

**Issue by majorkazer** [klarman-cell-observatory/cumulus#162]
I am running cellranger_workflow with v3.1 10x data where we used TotalSeqB antibodies for sample hashing. The workflow runs without any errors, but the output csv file for the adt feature counts is missing the majority (99%) of the cell barcodes that were found in the `cellranger count` step. My associated samplesheets are attached, and 5% of my reads were from the antibody library.

Are there intermediate files being created during `cumulus adt` that are not in the output from the workflow? I.e. do the cells that don't appear in the antibody csv file have 0 aligned barcodes? 

Since, to my understanding, `cumulus adt` is run separately from `cellranger count`, I ran a test alignment on the data using `cellranger 5.0.0` using the combined gene expression and antibody barcode calling. This approach reported hundreds to thousands of antibody barcodes per cell, and only ~3% of cells lacked antibody barcodes altogether.

Any thoughts on the discrepancy between these two approaches? And are there any plans to incorporate the simultaneous gene expression and antibody barcode calling available in `cellranger 5.0.0`?

[antibody_index.txt](https://github.com/klarman-cell-observatory/cumulus/files/5946798/antibody_index.txt)
[sample_sheet_merge.txt](https://github.com/klarman-cell-observatory/cumulus/files/5946803/sample_sheet_merge.txt)

**Comment by bli25broad** [comment]
Hi @majorkazer , sorry for the late reply. 

This is weird. We do not expect such a huge discrepancy between our adt approach and the simultaneous calling approach. I wonder if it is possible that you can share your workspace with us for debugging purpose?

Thanks,
Bo

**Comment by majorkazer** [comment]
Hi Bo,

Thanks for getting back to me. I should also note this is a single-index experiment using indices from 10x run on a NextSeq. I was unsure if I should try to reverse complement the indices since it was taken from the 10x index well (i.e. has 4 different indices mixed in).

I have shared you on another, cleaner workspace with a similar sample that had the same issue (~250/19000 cells w/ hashes).

Thanks,
Sam

**Comment by bli25broad** [comment]
@majorkazer Issue is fixed. The new ADT count vector has a 0.9995 Pearson correlation with the cellranger-produced count vector. Please try out cellranger_workflow snapshot 17 (https://cumulus.readthedocs.io/en/latest/versions.html).
