### ISSUE TITLE
star_solo feature request '--soloCellFilter' option functionality

### ISSUE THREAD

**Issue by benemead** [klarman-cell-observatory/cumulus#202]
Hi,

Thank you for making star solo available on terra!

I've been using the pipeline extensively, and have noticed that on some samples the cell filtering can be overly conservative. 

Digging through the [STARsolo documentation](https://github.com/alexdobin/STAR/blob/master/docs/STARsolo.md) I see there are 2 options for Cell filtering: `--soloCellFilter CellRanger2.2` (default) and `--soloCellFilter EmptyDrops_CR`.

Since the current .wdl doesn't specify, I'm assuming the pipeline presently runs the default? 

Would it be possible to update with the functionality to choose? (Choosing the non-default also looks like it requires additional parameters to be specified)

**Comment by yihming** [comment]
Hi @benemead ,

Thanks for reaching, and for your feedback!

It looks like `--soloCellFilter EmptyDrops_CR` was introduced in v2.7.8a, while our current support is only v2.7.6a, so you are correct that our workflow runs with the default.

We'll work on updating the workflow with your feature request, and let you know once it's ready.


Sincerely,
Yiming

**Comment by yihming** [comment]
Hi @ctzouanas and @benemead ,

Since `soloCellFilter` is currently exposed to users in STARsolo workflow ("master" version), as well as we've provided support for STAR v2.7.9a, may I close this issue?


Sincerely,
Yiming

**Comment by benemead** [comment]
Yep! Thanks so much!
