### ISSUE TITLE
demultiplexing fails after Config

### ISSUE THREAD

**Issue by majorkazer** [klarman-cell-observatory/cumulus#207]
Hello!

I am trying to run the `demultiplexing` workflow but am running into the following error in the Job Manager:
![Screen Shot 2021-09-15 at 3 38 25 PM](https://user-images.githubusercontent.com/15038988/133498435-d5a63d6d-891c-4e62-8383-0fbf383cfc60.png)

The workflow seems to fail immediately following the Config task and can't seem to see an empty pooling_ids variable. I am using this workflow only for cell-hashing data, so I shouldn't have any genetic pooling information. My sample-sheet and input json are attached as well.

Thanks!

[cumulus_naive_sample_sheet_demux.csv](https://github.com/klarman-cell-observatory/cumulus/files/7172788/cumulus_naive_sample_sheet_demux.csv)
[demultiplexing_inputs.json.txt](https://github.com/klarman-cell-observatory/cumulus/files/7172796/demultiplexing_inputs.json.txt)

**Comment by yihming** [comment]
Hello @majorkazer ,

This is a known issue which has been resolved in pull request #201 . However, since we are working on workflow inputs changes, we haven't updated demultiplexing workflow snapshot. 

I just updated it, and please use snapshot 32 to see if the issue goes away.


Sincerely,
Yiming

**Comment by majorkazer** [comment]
Hi @yihming,

Thanks for updating the workflow snapshot! Everything seems to be working now.

Best,
Sam
