### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by wjyzidane** [klarman-cell-observatory/cumulus#3]
Thanks for help me clean the previous error but I got another error as below:

Task cellranger_atac_mkfastq.run_cellranger_atac_mkfastq:NA:1 failed. The job was stopped before the command finished. PAPI error code 2. Execution failed: pulling image: docker pull: running ["docker" "pull" "gcr.io/sccloud-prod/cellranger-atac:1.0.1"]: exit status 1 (standard error: "Error response from daemon: pull access denied for gcr.io/sccloud-prod/cellranger-atac, repository does not exist or may require 'docker login': denied: Permission denied for \"1.0.1\" from request \"/v2/sccloud-prod/cellranger-atac/manifests/1.0.1\".\n")

**Comment by joshua-gould** [comment]
Non Broad Institute members need to provide their own docker if they wish
to run cellrankger mkfastq. Please see
https://cumulus-doc.readthedocs.io/en/latest/bcl2fastq.html

**Comment by wjyzidane** [comment]
I am a Broad Institute member may I know why there is still a permission issue?

**Comment by joshua-gould** [comment]
There are still some issues with Terra and the all Broad users group.
Please contact Terra support and request to be added to
all_broad_users@firecloud.org group.

**Comment by wjyzidane** [comment]
I did use Broad email to login. I run cell-ranger on Broad sever as an alternative right now.

**Comment by bli25broad** [comment]
Hi Jingyi,

You only need to run the mkfastq step on Broad server. See here for an
example:
https://cumulus-doc.readthedocs.io/en/latest/cellranger.html#only-run-the-count-part

At the same time, please follow Josh's comment to email Terra team to add
you to all_broad_users@firecloud.org

Best,
Bo

**Comment by wjyzidane** [comment]
Will do. Thanks!

**Comment by joshua-gould** [comment]
Yes, sorry our documentation was out of date. Please use cumulus/cellranger_workflow version 1 which supports cellranger atac version 1.1.0.

**Comment by wjyzidane** [comment]
Where can I find the cumulus/cellranger_workflow version 1?

**Comment by joshua-gould** [comment]
https://portal.firecloud.org/?return=terra#methods/cumulus/cellranger_workflow/1

**Comment by wjyzidane** [comment]
Looks like there is still some problem:

Task cellranger_atac_mkfastq.run_cellranger_atac_mkfastq:NA:1 failed. The job was stopped before the command finished. PAPI error code 2. Execution failed: pulling image: docker pull: running ["docker" "pull" "gcr.io/broad-cumulus/cellranger-atac:1.1.0"]: exit status 1 (standard error: "Error response from daemon: pull access denied for gcr.io/broad-cumulus/cellranger-atac, repository does not exist or may require 'docker login': denied: Permission denied for \"1.1.0\" from request \"/v2/broad-cumulus/cellranger-atac/manifests/1.1.0\".\n”)

**Comment by joshua-gould** [comment]
Can you please execute https://api.firecloud.org/#!/Groups/getGroups to see what groups you're a member of? You need to click authorize in the upper right corner before executing. Thanks.

**Comment by wjyzidane** [comment]
Thanks for your reply and it looks a little bit complicated to me. I think I will chat with Bo some time later. Maybe we can figure it out then.

**Comment by joshua-gould** [comment]
I'm also happy to meet with you.

**Comment by wjyzidane** [comment]
Look forward. I think we will meet Bo next Thursday 4:30 at Broad.
