### ISSUE TITLE
400 ERROR

### ISSUE THREAD

**Issue by mav-mit** [klarman-cell-observatory/cumulus#304]
I'm getting a 400 error trying to access regev lab 

Please consider adding a -u <project-id> flag when copying / pulling from Request-Pays workspaces. 

More info here:
https://support.terra.bio/hc/en-us/articles/360029801491-Using-Requester-Pays-workspaces-buckets

**Comment by slowkow** [comment]
Hard-coding the path to the genome files is not a good idea. The resource is not guaranteed to be there in the future:

https://github.com/klarman-cell-observatory/cumulus/blob/bb155c41320a4b2ee21be3335e25c6e3ffc94106/workflows/cellranger/cellranger_workflow.wdl#L97

Something changed recently:
- Previously, the `read_map()` WDL function worked OK.
- Currently, the `read_map()` function does not set the project ID for the requester to pay.

**Comment by yihming** [comment]
@mav-mit 

Thanks for reporting this issue. There is another one similar to yours (#303).

We are reaching out to Terra support team to figure out a solution to it. Ideally, the issue could be fixed at Cromwell side to make `read_map` function work for files on requester pay buckets again.

We don't explicitly use `gsutil` to fetch those files in our WDL, and asking users to manually specify their project ID in `-u` option could be annoying. 

We'll keep you posted on any progress regarding this issue fixing.


Sincerely,
Yiming

**Comment by yihming** [comment]
The Terra team is working on it. You can track their status at https://support.terra.bio/hc/en-us/articles/4447388269851.

**Comment by mav-mit** [comment]
Thank you @slowkow and @yihming for responding. As a workaround to the issue I created my own reference genome. This fixed the 400 error but then it died with <Signals.SIGSEGV: 11>. run_starsolo.log attached

What do you guys suggest? 
Adding @bli25 too since I also pinged him via email. 

Thanks again! 

[3b80e843-5890-421a-82bd-daab8e874f10_starsolo_workflow_68e01210-4c6e-4913-92af-80eb5f76364e_call-starsolo_count_shard-1_starsolo_count_1cc2783f-6e86-40c1-ac14-cb5897132365_call-run_starsolo_run_starsolo.txt](https://github.com/klarman-cell-observatory/cumulus/files/8120615/3b80e843-5890-421a-82bd-daab8e874f10_starsolo_workflow_68e01210-4c6e-4913-92af-80eb5f76364e_call-starsolo_count_shard-1_starsolo_count_1cc2783f-6e86-40c1-ac14-cb5897132365_call-run_starsolo_run_starsolo.txt)

**Comment by yihming** [comment]
@mav-mit 

The 400 error has been fixed earlier today.

**Comment by mav-mit** [comment]
Yes. Thank you!

**Comment by yihming** [comment]
Hi @mav-mit ,

Just let you know that I've replied to both you and Constantine today about the "<Signals.SIGSEGV: 11>" (i.e. C++ segmentation fault) issue when running STARsolo workflow. Please follow my suggestions to see if the issue could be resolved, and let me know if not.


Sincerely,
Yiming
