### ISSUE TITLE
not been declared as a valid return code

### ISSUE THREAD

**Issue by xzlandy** [klarman-cell-observatory/cumulus#4]
Hello,

I used cellranger_workflow on Terra for 10x public dataset (5k Peripheral blood mononuclear cells (PBMCs) from a healthy donor with cell surface proteins (v3 chemistry)). However, both cellranger_count and scCloud_adt report errors. And I have no idea how to use it.

Failure Messages are list as below.

cellranger_count
Job cellranger_count.run_cellranger_count:NA:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.

scCloud_adt
Job scCloud_adt.run_generate_count_matrix_ADTs:NA:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.

**Comment by bli25broad** [comment]
Can you share your sample sheets?

**Comment by xzlandy** [comment]
The sample sheets is as follow.

Sample,Reference,Flowcell,Chemistry,DataType,FeatureBarcodeFile
5k_pbmc_protein_v3_gex,GRCh38_v3.0.0,gs://fc-017b6faa-b021-4fb4-be37-2c38d420b338/5k_pbmc_protein_v3_fastqs/5k_pbmc_protein_v3_gex_fastqs,SC3Pv3,rna
5k_pbmc_protein_v3_antibody,GRCh38_v3.0.0,gs://fc-017b6faa-b021-4fb4-be37-2c38d420b338/5k_pbmc_protein_v3_fastqs/5k_pbmc_protein_v3_antibody_fastqs,SC3Pv3,adt,gs://fc-017b6faa-b021-4fb4-be37-2c38d420b338/5k_pbmc_protein_v3_feature_ref.csv
