### ISSUE TITLE
dropseq_workflow not enough diskspace for fastq.gz's smaller than 5GB

### ISSUE THREAD

**Issue by jggatter** [klarman-cell-observatory/cumulus#6]
Hi,

I noticed that for two downsampled fastq.gz’s I am trying to align (R1=2.6 GB, R2=4.13 GB) that generate_count_config only hands off 2 GB of disk space to prepare_fastq, which is nearly not enough so it crashes. 2 GB is also passed for fastq.gz's that are smaller for this. Could a higher bare minimum be set to work for these cases?

Thanks,
James

**Comment by joshua-gould** [comment]
This seems like a bug. The intended behavior is to allocate
(sum_of_fastq_size +1) * 4.

**Comment by bli25broad** [comment]
@joshua-gould , can you confirm that we have fixed this bug?

Thanks,
Bo

**Comment by joshua-gould** [comment]
Yes,
