### ISSUE TITLE
Cumulus workflow v6 not working for my Seq-Well data

### ISSUE THREAD

**Issue by jggatter** [klarman-cell-observatory/cumulus#7]
Hi,

I brought up this issue outside of Github a few weeks ago but it seems changes have not fixed the problem.  

Here is the full log without localization & delocalization steps.
```
Usage:
pegasus aggregate_matrix <csv_file> <output_name> [--restriction <restriction>... --attributes <attributes> --google-cloud --select-only-singlets --minimum-number-of-genes <ngene>]
pegasus aggregate_matrix -h
pegasus aggregate_matrix /cromwell_root/fc-secure-06a1d647-0ffd-410c-af2e-8a38acfede12/IRA_FASTQs/count_matrix.csv cumulus --google-cloud --minimum-number-of-genes 100 --genome mm10
Traceback (most recent call last):
File "<stdin>", line 18, in <module>
File "/opt/conda/lib/python3.7/subprocess.py", line 347, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pegasus', 'aggregate_matrix', '/cromwell_root/fc-secure-06a1d647-0ffd-410c-af2e-8a38acfede12/IRA_FASTQs/count_matrix.csv', 'cumulus', '--google-cloud', '--minimum-number-of-genes', '100', '--genome', 'mm10']' returned non-zero exit status 1.
```
I'm not able to troubleshoot this myself because the CalledProcessError is not descriptive. It might be good to `except` the error and inform the user more precisely of where they might have gone wrong.  

Here is my configuration file. Github would only allow me to upload it as a .txt file, sorry.
[jggatter_cumulus.txt](https://github.com/klarman-cell-observatory/cumulus/files/3842184/jggatter_cumulus.txt)

Let me know what your thoughts are!

Thanks!
James

**Comment by bli25broad** [comment]
Hi @jggatter,

Thanks for reporting this error to us. We also have a google support group: cumulus-support@googlegroups.com

Can you send me the count_matrix.csv file and your config file through the support group? 

Thanks,
Bo

**Comment by jggatter** [comment]
Hi @bli25broad, I'm unable to find this group in a google groups search, do you have a link? And yes I'll make sure to add the count_matrix too, sorry I forgot about that!

**Comment by jggatter** [comment]
Neither of these worked:
[count_matrix.txt](https://github.com/klarman-cell-observatory/cumulus/files/3843215/count_matrix.txt)
[count_matrix (1).txt](https://github.com/klarman-cell-observatory/cumulus/files/3843214/count_matrix.1.txt)

**Comment by bli25broad** [comment]
Hi @jggatter , 

Sorry, I just make it public available, can you try it again? cumulus-support@googlegroups.com

In addition, I looked at your count_matrix.csv file, it looks good.  Actually, I guess that I know what's the reason. We can fix it today. But I still encourage you to emails us using the google group.

Best,
Bo

**Comment by jggatter** [comment]
I applied to the group, will post there in the future!

Thank you so much! Please let me know when I should try the workflow again!

**Comment by bli25broad** [comment]
Fixed.
